/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mky96
 */
package com.helwan.event_management_system.UI.admin;

import com.helwan.event_management_system.data.FileManager;
import com.helwan.event_management_system.models.user;
import java.util.ArrayList;

public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
    private FileManager fileManager;
    private ArrayList<user> usersList;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        fileManager = new FileManager(
            FileManager.getResourcePath("data/users.txt"),
            FileManager.getResourcePath("data/booking.txt")
        );
        loadUsersFromFile();
tblUsers.getTableHeader().setDefaultRenderer(new javax.swing.table.DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        
        setBackground(new java.awt.Color(15, 23, 42)); 
        setForeground(java.awt.Color.WHITE);         
        setFont(new java.awt.Font("Segoe UI", java.awt.Font.CENTER_BASELINE, 14)); 
       
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        
        return this;
    }
}); 

tblUsers.setDefaultEditor(Object.class, null);

tblUsers.setBackground(new java.awt.Color(30, 41, 59)); 
tblUsers.setForeground(java.awt.Color.WHITE); 

tblUsers.setSelectionBackground(new java.awt.Color(20, 184, 166)); 
tblUsers.setSelectionForeground(java.awt.Color.WHITE);
jScrollPane1.getViewport().setBackground(new java.awt.Color(30, 41, 59));
tblUsers.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAdduser = new javax.swing.JButton();
        btnDeleteuser = new javax.swing.JButton();
        btnUpdateuser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 41, 52));

        tblUsers.setBackground(new java.awt.Color(44, 52, 78));
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Role", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        btnAdduser.setBackground(new java.awt.Color(0, 102, 102));
        btnAdduser.setForeground(new java.awt.Color(255, 255, 255));
        btnAdduser.setText("Add");
        btnAdduser.addActionListener(this::btnAdduserActionPerformed);

        btnDeleteuser.setBackground(new java.awt.Color(153, 0, 0));
        btnDeleteuser.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteuser.setText("Delete");
        btnDeleteuser.addActionListener(this::btnDeleteuserActionPerformed);

        btnUpdateuser.setBackground(new java.awt.Color(102, 102, 0));
        btnUpdateuser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateuser.setText("Update");
        btnUpdateuser.addActionListener(this::btnUpdateuserActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdduser)
                .addGap(52, 52, 52)
                .addComponent(btnDeleteuser)
                .addGap(40, 40, 40)
                .addComponent(btnUpdateuser)
                .addGap(147, 147, 147))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdduser)
                    .addComponent(btnDeleteuser)
                    .addComponent(btnUpdateuser))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnDeleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteuserActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblUsers.getModel();
        int selectedRow = tblUsers.getSelectedRow();
        if (selectedRow != -1) {
            // Get user email to find and remove from list
            String userEmail = model.getValueAt(selectedRow, 1).toString();
            
            // Remove from list
            usersList.removeIf(u -> u.getEmail().equals(userEmail));
            
            // Remove from table
            model.removeRow(selectedRow);
            
            // Save changes to file
            fileManager.savingUser(usersList, fileManager.getUserFilePath());
            
            javax.swing.JOptionPane.showMessageDialog(this, "User Deleted Successfully!"); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a user first!");
        }
    }//GEN-LAST:event_btnDeleteuserActionPerformed

    private void btnAdduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdduserActionPerformed
        javax.swing.JTextField txtName = new javax.swing.JTextField();
        javax.swing.JTextField txtEmail = new javax.swing.JTextField();
        javax.swing.JTextField txtPass = new javax.swing.JTextField();

        String[] roles = {"Customer", "PM", "SP", "Admin"};
        javax.swing.JComboBox<String> cmbRole = new javax.swing.JComboBox<>(roles);

        Object[] message = {
            "Full Name:", txtName,
            "Email:", txtEmail,
            "Role:", cmbRole,
            "Password:", txtPass
        };

        while(true) {
            int option = javax.swing.JOptionPane.showConfirmDialog(this, message, "Add New User", javax.swing.JOptionPane.OK_CANCEL_OPTION);
            if (option != javax.swing.JOptionPane.OK_OPTION) {
                break; 
            }

            String name = txtName.getText();
            String email = txtEmail.getText();
            String pass = txtPass.getText();
            String role = cmbRole.getSelectedItem().toString();
            
            if (name.isEmpty() || email.isEmpty() || pass.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill all fields! ");
            } else if (!email.contains("@")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid Email! Must contain '@' ");
            } else if (pass.length() < 6) {
                javax.swing.JOptionPane.showMessageDialog(this, "Password is too weak! Must be at least 6 characters ");
            } else {
                // Generate new ID
                int newId = fileManager.generateUserId(usersList);
                
                // Create user object based on role
                user newUser = createUserByRole(newId, name, email, pass, role);
                
                // Add to list
                usersList.add(newUser);
                
                // Add to table
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblUsers.getModel();
                model.addRow(new Object[]{name, email, role, pass});
                
                // Save to file
                fileManager.savingUser(usersList, fileManager.getUserFilePath());
                
                javax.swing.JOptionPane.showMessageDialog(this, "User Added Successfully! ");
                
                break; 
            }
        }
    }//GEN-LAST:event_btnAdduserActionPerformed

    private void btnUpdateuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateuserActionPerformed
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblUsers.getModel();
        int selectedRow = tblUsers.getSelectedRow();

        if (selectedRow != -1) {
            String oldEmail = model.getValueAt(selectedRow, 1).toString();
            
            javax.swing.JTextField txtName = new javax.swing.JTextField(model.getValueAt(selectedRow, 0).toString());
            javax.swing.JTextField txtEmail = new javax.swing.JTextField(model.getValueAt(selectedRow, 1).toString());
            String[] roles = {"Customer", "PM", "SP", "Admin"}; 
            javax.swing.JComboBox<String> cmbRole = new javax.swing.JComboBox<>(roles);
            String currentRole = model.getValueAt(selectedRow, 2).toString();
            cmbRole.setSelectedItem(currentRole);

            javax.swing.JTextField txtPass = new javax.swing.JTextField(model.getValueAt(selectedRow, 3).toString());
            Object[] message = {
                "Name:", txtName, 
                "Email:", txtEmail,
                "Role:", cmbRole,      
                "Password:", txtPass   
            }; 

            int option = javax.swing.JOptionPane.showConfirmDialog(this, message, "Update User", javax.swing.JOptionPane.OK_CANCEL_OPTION);
            
            if (option == javax.swing.JOptionPane.OK_OPTION) {
                String newName = txtName.getText();
                String newEmail = txtEmail.getText();
                String newRole = cmbRole.getSelectedItem().toString();
                String newPass = txtPass.getText();
                
                // Update in table
                model.setValueAt(newName, selectedRow, 0);
                model.setValueAt(newEmail, selectedRow, 1);
                model.setValueAt(newRole, selectedRow, 2); 
                model.setValueAt(newPass, selectedRow, 3); 
                
                // Update in list
                for (user u : usersList) {
                    if (u.getEmail().equals(oldEmail)) {
                        u.setName(newName);
                        u.setEmail(newEmail);
                        u.setPassword(newPass);
                        u.setRole(newRole);
                        break;
                    }
                }
                
                // Save to file
                fileManager.savingUser(usersList, fileManager.getUserFilePath());
                
                javax.swing.JOptionPane.showMessageDialog(this, "User Updated Successfully! ");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a user to update! ");
        }
    }//GEN-LAST:event_btnUpdateuserActionPerformed

    private void loadUsersFromFile() {
        usersList = fileManager.loadUsers();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblUsers.getModel();
        model.setRowCount(0); // Clear existing rows
        
        for (user u : usersList) {
            model.addRow(new Object[]{
                u.getName(),
                u.getEmail(),
                u.getRole(),
                u.getPassword()
            });
        }
    }
    
    private user createUserByRole(int id, String name, String email, String password, String role) {
        switch (role.toLowerCase()) {
            case "customer":
                return new com.helwan.event_management_system.models.customer(id, name, email, password, "", "Customer");
            case "pm":
                return new com.helwan.event_management_system.models.PM(id, name, email, password, "", "PM", "");
            case "sp":
                return new com.helwan.event_management_system.models.SP(id, name, email, password, "", "SP");
            case "admin":
                return new com.helwan.event_management_system.models.admin(id, name, email, password, "Admin");
            default:
                return new user(id, name, email, password, role);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdduser;
    private javax.swing.JButton btnDeleteuser;
    private javax.swing.JButton btnUpdateuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
