package com.helwan.event_management_system.UI;
import java.io.*;
import java.awt.*;
import javax.swing.*;

import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import com.helwan.event_management_system.data.FileManager;
import com.helwan.event_management_system.models.Booking;
import com.helwan.event_management_system.models.Event;
import com.helwan.event_management_system.models.customer;
import java.util.ArrayList;

/**
 *
 * @author Copy Center
 */
public class ProjectManager extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjectManager.class.getName());

    /**
     * Creates new form ProjectManager
     */
    public ProjectManager() {
        initComponents();
        loadBookings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Project Manager", jPanel2);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(15, 23, 42));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2024", "razan", "wedding", "penned"},
                {"2023", "rahma", "party", "submitted"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Booking ID", "Customer", "Event Type ", "Status"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(15, 23, 42));
        jTable1.setShowGrid(true);
        jTable1.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Assign to Service Provider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("Contact Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Load bookings from file and populate the table
     */
    private void loadBookings() {
        try {
            FileManager fileManager = new FileManager(
                FileManager.getResourcePath("data/users.txt"),
                FileManager.getResourcePath("data/booking.txt")
            );

            // Load users, customers, and events
            ArrayList<com.helwan.event_management_system.models.user> users = fileManager.loadUsers();
            ArrayList<Event> events = fileManager.loadEvents();
            
            // Extract customer objects from users
            ArrayList<customer> customers = new ArrayList<>();
            for (com.helwan.event_management_system.models.user u : users) {
                if (u instanceof customer) {
                    customers.add((customer) u);
                }
            }
            
            // Load bookings with populated customer and event lists
            ArrayList<Booking> bookings = fileManager.loadBookings(customers, events);
            System.out.println("DEBUG: Loaded " + bookings.size() + " bookings from " + customers.size() + " customers and " + events.size() + " events");

            // Clear existing rows
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // Add booking data to table
            for (Booking booking : bookings) {
                Object[] row = {
                    booking.getBookingId(),
                    booking.getCustomerId().getName(),
                    booking.getEventId().getType(),
                    booking.getStatus()
                };
                model.addRow(row);
            }

        } catch (Exception e) {
            System.out.println("Error loading bookings: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            FileManager fileManager = new FileManager(
                FileManager.getResourcePath("data/users.txt"),
                FileManager.getResourcePath("data/booking.txt")
            );

            // Load users, customers, and events
            ArrayList<com.helwan.event_management_system.models.user> users = fileManager.loadUsers();
            ArrayList<Event> events = fileManager.loadEvents();
            ArrayList<customer> customers = new ArrayList<>();
            for (com.helwan.event_management_system.models.user u : users) {
                if (u instanceof customer) customers.add((customer) u);
            }
            ArrayList<Booking> bookings = fileManager.loadBookings(customers, events);

            boolean updated = false;
            for (Booking booking : bookings) {
                if ("New".equalsIgnoreCase(booking.getStatus())) {
                    booking.setStatus("Processing");
                    // Simulate sending to SP (print to console)
                    System.out.println("Assigned booking ID " + booking.getBookingId() + " to Service Provider.");
                    updated = true;
                }
            }
            if (updated) {
                fileManager.savingBooking(bookings, fileManager.getBookingFilePath());
                javax.swing.JOptionPane.showMessageDialog(this, "All new bookings assigned to Service Provider and set to Processing.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No new bookings to assign.");
            }
            loadBookings(); // Refresh table
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error assigning bookings: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        openChatWindow();
    }//GEN-LAST:event_jButton2ActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProjectManager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

        // ==========================================================
    // ============= كود الشات الخاص بالمدير (PM) ===============
    // ==========================================================

    // دالة فتح الشات
    private void openChatWindow() {
        // 1. تصميم الشباك
        JDialog chatDialog = new JDialog(this, "Customer Support Chat", true);
        chatDialog.setSize(400, 500);
        chatDialog.setLayout(new BorderLayout());
        chatDialog.setLocationRelativeTo(this);

        // 2. مساحة عرض الرسايل
        JTextArea chatArea = new JTextArea();
        chatArea.setEditable(false);
        chatArea.setFont(new Font("Monospaced", Font.PLAIN, 14));
        JScrollPane scroll = new JScrollPane(chatArea);
        chatDialog.add(scroll, BorderLayout.CENTER);

        // 3. مساحة الكتابة والأزرار
        JPanel bottomPanel = new JPanel(new BorderLayout());
        JTextField inputField = new JTextField();
        JButton btnSend = new JButton("Reply");
        JButton btnRefresh = new JButton("Refresh");

        JPanel btnPanel = new JPanel(new GridLayout(1, 2));
        btnPanel.add(btnSend);
        btnPanel.add(btnRefresh);

        bottomPanel.add(inputField, BorderLayout.CENTER);
        bottomPanel.add(btnPanel, BorderLayout.EAST);
        chatDialog.add(bottomPanel, BorderLayout.SOUTH);

        // 4. تعريف الهوية (أنا المدير بكلم الزبون)
        String myName = "PM";       // أنا مين
        String otherSide = "Customer"; // بكلم مين (ممكن نخليه عام)

        // حمل الرسايل أول ما تفتح
        loadMessagesFromFile(chatArea, myName);

        // --- زرار الإرسال ---
        btnSend.addActionListener(e -> {
            String msg = inputField.getText().trim();
            if (!msg.isEmpty()) {
                saveMessageToFile(myName, otherSide, msg); // PM -> Customer
                inputField.setText("");
                loadMessagesFromFile(chatArea, myName);
            }
        });

        // --- زرار الريفريش ---
        btnRefresh.addActionListener(e -> {
            loadMessagesFromFile(chatArea, myName);
        });

        chatDialog.setVisible(true);
    }

    // دالة قراءة الرسائل من الفايل
    private void loadMessagesFromFile(JTextArea area, String me) {
        area.setText(""); // فضي الشاشة
        File file = new File("messages.txt");
        if (!file.exists()) return;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 3) {
                    String sender = parts[0];
                    String receiver = parts[1];
                    String msg = parts[2];

                    // اعرض الرسالة لو تخصني (سواء أنا باعتها أو جيالي)
                    if (sender.equalsIgnoreCase(me) || receiver.equalsIgnoreCase(me)) {
                        if (sender.equalsIgnoreCase(me)) {
                            area.append("Me (PM): " + msg + "\\n");
                        } else {
                            area.append("Customer: " + msg + "\\n");
                        }
                        area.append("-----------------\\n");
                    }
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    // دالة حفظ الرسائل في الفايل
    private void saveMessageToFile(String sender, String receiver, String msg) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("messages.txt", true))) {
            bw.write(sender + "," + receiver + "," + msg);
            bw.newLine();
        } catch (IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error sending message!");
        }
    }

    
}

