/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.helwan.event_management_system.UI.booking;

import com.helwan.event_management_system.UI.login.Login;
import com.helwan.event_management_system.data.FileManager;
import com.helwan.event_management_system.logic.EmailService;
import com.helwan.event_management_system.logic.SessionManager;
import com.helwan.event_management_system.models.Booking;
import com.helwan.event_management_system.models.Event;
import com.helwan.event_management_system.models.customer;
import com.helwan.event_management_system.models.Event;
import com.helwan.event_management_system.models.user;

import java.text.ParseException;
import java.util.ArrayList;

/**
 *
 * @author Adham
 */
public class EVentBookForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EVentBookForm.class.getName());

    /**
     * Creates new form test
     */
    public EVentBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        eventAdditionalDetailsScr = new javax.swing.JScrollPane();
        enentAdditionalDetailstxt = new javax.swing.JTextArea();
        Header = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        eventGuestCount = new javax.swing.JSpinner();
        eventTypeComboBox = new javax.swing.JComboBox<>();
        evDate = new javax.swing.JLabel();
        evType = new javax.swing.JLabel();
        evlocation = new javax.swing.JLabel();
        evGuestcount = new javax.swing.JLabel();
        evAdditionalDetails = new javax.swing.JLabel();
        BookNowBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        eventDateField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));

        jPanel3.setBackground(new java.awt.Color(15, 23, 42));

        jPanel1.setBackground(new java.awt.Color(44, 52, 78));

        enentAdditionalDetailstxt.setColumns(20);
        enentAdditionalDetailstxt.setRows(5);
        eventAdditionalDetailsScr.setViewportView(enentAdditionalDetailstxt);

        Header.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setText("Booking Form");

        jComboBox2.setMaximumRowCount(4);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alexandria", "Aswan", "Asyut", "Beheira", "Beni Suef", "Cairo", "Dakahlia", "Damietta", "Fayoum", "Gharbia", "Giza", "Ismailia", "Kafr El Sheikh", "Luxor", "Matruh", "Minya", "Monufia", "New Valley (Al Wadi Al Jadid)", "North Sinai", "Port Said", "Qalyubia", "Qena", "Red Sea (Al Bahr Al Ahmar)", "Sharqia", "Sohag", "South Sinai", "Suez" }));

        eventGuestCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        eventTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wedding", "Birthday", "Conference", " " }));
        eventTypeComboBox.addActionListener(this::eventTypeComboBoxActionPerformed);

        evDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evDate.setForeground(new java.awt.Color(255, 255, 255));
        evDate.setText("Event Date");

        evType.setBackground(new java.awt.Color(255, 255, 255));
        evType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evType.setForeground(new java.awt.Color(255, 255, 255));
        evType.setText("Event Type");

        evlocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evlocation.setForeground(new java.awt.Color(255, 255, 255));
        evlocation.setText("Event Location");

        evGuestcount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evGuestcount.setForeground(new java.awt.Color(255, 255, 255));
        evGuestcount.setText("Guest Count");

        evAdditionalDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evAdditionalDetails.setForeground(new java.awt.Color(255, 255, 255));
        evAdditionalDetails.setText("Additional Details");

        BookNowBtn.setText("Book Now");
        BookNowBtn.addActionListener(this::BookNowBtnActionPerformed);

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(this::ClearBtnActionPerformed);

        try {
            eventDateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        eventDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eventDateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                eventDateFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(evDate)
                                    .addComponent(evType))
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ClearBtn)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(evGuestcount)
                                        .addComponent(evlocation)
                                        .addComponent(evAdditionalDetails)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventGuestCount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventAdditionalDetailsScr, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookNowBtn)
                            .addComponent(eventTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Header)
                        .addGap(186, 186, 186))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evType)
                    .addComponent(eventTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evDate)
                    .addComponent(eventDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(evlocation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evGuestcount)
                    .addComponent(eventGuestCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evAdditionalDetails)
                    .addComponent(eventAdditionalDetailsScr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookNowBtn)
                    .addComponent(ClearBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventTypeComboBoxActionPerformed

    private void BookNowBtnActionPerformed(java.awt.event.ActionEvent evt) {

        // 1️⃣ Read form data
        String eventType = eventTypeComboBox.getSelectedItem().toString();
        String eventDate = eventDateField.getText();
        String location = jComboBox2.getSelectedItem().toString();
        int guestCount = (int) eventGuestCount.getValue();
        String details = enentAdditionalDetailstxt.getText();

        if (eventDate.equals("-  -") || eventDate.length() < 10 || !isValidDate(eventDate)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Invalid date! Please check the day/month and ensure the year is 2025 or later.", 
                "Date Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        // 2️⃣ Validate fields
        if (eventType == null || eventType.isEmpty()
                || eventDate.trim().isEmpty()
                || location == null || location.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please fill all required fields"
            );
            return;
        }

        // 3️⃣ Ensure user is logged in
        if (!SessionManager.isLoggedIn()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Session expired. Please login again."
            );
            new Login().setVisible(true);
            this.dispose();
            return;
        }

        // 4️⃣ FileManager
        FileManager fm = new FileManager(
            "src/main/resources/data/users.txt",
            "src/main/resources/data/booking.txt"
        );

        // 5️⃣ Load existing bookings
        ArrayList<Booking> bookings = fm.loadBookings(
            new ArrayList<>(),
            new ArrayList<>()
        );

        // 6️⃣ Generate Booking ID
        int bookingId = fm.generateBookingId(bookings);

        // 7️⃣ Create Event
        Event newEvent = new Event(
            bookingId,        // temporary eventId
            eventType,
            eventDate,
            location,
            guestCount,
            details
        );

        // 8️⃣ Booking metadata
        String status = "Completed";
        double totalPrice = 150.0; // can be calculated later

        // 9️⃣ Create Booking (LOGGED-IN CUSTOMER)
        Booking booking = new Booking(
            bookingId,
            (customer) SessionManager.getCurrentUser(),
            newEvent,
            status,
            totalPrice
        );

        // 🔟 Save booking
        bookings.add(booking);
        fm.savingBooking(bookings, fm.getBookingFilePath());

        // 1️⃣1️⃣ Confirmation
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Booking Created Successfully!"
        );

        // 1️⃣3️⃣ Send email asynchronously to logged-in customer
        user user = SessionManager.getCurrentUser();

        // Create EmailService object passing the customer email
        EmailService emailService = new EmailService(user.getEmail());

        // Call sendBookingConfirmation on the object
        new Thread(() -> emailService.sendBookingConfirmation(
                user.getName(),
                eventType,
                eventDate,
                location,
                bookingId
        )).start();


        // 1️⃣2️⃣ Navigate to MyBookings
        new MyBookingsScreen().setVisible(true);
        this.dispose();
}                                          

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
                                        
    eventDateField.setText("");           
    enentAdditionalDetailstxt.setText("");
    eventGuestCount.setValue(1);      
    eventTypeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void eventDateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eventDateFieldFocusGained
                                       
    if (eventDateField.getText().equals("DD-MM-YYYY")) {
        eventDateField.setText("");
        eventDateField.setForeground(new java.awt.Color(0, 0, 0)); 
    }

    }//GEN-LAST:event_eventDateFieldFocusGained

    private void eventDateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eventDateFieldFocusLost
                                           
    if (eventDateField.getText().trim().equals("")) {
        eventDateField.setText("DD-MM-YYYY");
        eventDateField.setForeground(new java.awt.Color(153, 153, 153)); 
    }

    }//GEN-LAST:event_eventDateFieldFocusLost

private boolean isValidDate(String dateStr) {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
    sdf.setLenient(false);

    try {
       
        java.util.Date inputDate = sdf.parse(dateStr);
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(inputDate);
        int year = cal.get(java.util.Calendar.YEAR);

        return year >= 2025; 
    } catch (ParseException e) {
        return false;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookNowBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel Header;
    private javax.swing.JTextArea enentAdditionalDetailstxt;
    private javax.swing.JLabel evAdditionalDetails;
    private javax.swing.JLabel evDate;
    private javax.swing.JLabel evGuestcount;
    private javax.swing.JLabel evType;
    private javax.swing.JScrollPane eventAdditionalDetailsScr;
    private javax.swing.JFormattedTextField eventDateField;
    private javax.swing.JSpinner eventGuestCount;
    private javax.swing.JComboBox<String> eventTypeComboBox;
    private javax.swing.JLabel evlocation;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
