/*
* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.helwan.event_management_system.UI.booking;
import java.io.*;
import javax.swing.*;
import java.awt.*;
import com.helwan.event_management_system.UI.login.Login;
import com.helwan.event_management_system.data.FileManager;
import com.helwan.event_management_system.logic.EmailService;
import com.helwan.event_management_system.logic.SessionManager;
import com.helwan.event_management_system.models.Booking;
import com.helwan.event_management_system.models.Event;
import com.helwan.event_management_system.models.customer;
import com.helwan.event_management_system.models.Event;
import com.helwan.event_management_system.models.user;

import java.text.ParseException;
import java.util.ArrayList;

/**
 *
 * @author Adham
 */
public class EVentBookForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EVentBookForm.class.getName());

    /**
     * Creates new form test
     */
    public EVentBookForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        eventAdditionalDetailsScr = new javax.swing.JScrollPane();
        enentAdditionalDetailstxt = new javax.swing.JTextArea();
        Header = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        eventGuestCount = new javax.swing.JSpinner();
        eventTypeComboBox = new javax.swing.JComboBox<String>();
        evType = new javax.swing.JLabel();
        evlocation = new javax.swing.JLabel();
        evGuestcount = new javax.swing.JLabel();
        evAdditionalDetails = new javax.swing.JLabel();
        BookNowBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));

        jPanel3.setBackground(new java.awt.Color(15, 23, 42));

        jPanel1.setBackground(new java.awt.Color(44, 52, 78));

        enentAdditionalDetailstxt.setColumns(20);
        enentAdditionalDetailstxt.setRows(5);
        eventAdditionalDetailsScr.setViewportView(enentAdditionalDetailstxt);

        Header.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setText("Booking Form");

        jComboBox2.setMaximumRowCount(4);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Alexandria", "Aswan", "Asyut", "Beheira", "Beni Suef", "Cairo", "Dakahlia", "Damietta", "Fayoum", "Gharbia", "Giza", "Ismailia", "Kafr El Sheikh", "Luxor", "Matruh", "Minya", "Monufia", "New Valley (Al Wadi Al Jadid)", "North Sinai", "Port Said", "Qalyubia", "Qena", "Red Sea (Al Bahr Al Ahmar)", "Sharqia", "Sohag", "South Sinai", "Suez" }));

        eventGuestCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        eventTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Wedding", "Birthday", "Conference", " " }));
        eventTypeComboBox.addActionListener(this::eventTypeComboBoxActionPerformed);

        evType.setBackground(new java.awt.Color(255, 255, 255));
        evType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evType.setForeground(new java.awt.Color(255, 255, 255));
        evType.setText("Event Type");

        evlocation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evlocation.setForeground(new java.awt.Color(255, 255, 255));
        evlocation.setText("Event Location");

        evGuestcount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evGuestcount.setForeground(new java.awt.Color(255, 255, 255));
        evGuestcount.setText("Guest Count");

        evAdditionalDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        evAdditionalDetails.setForeground(new java.awt.Color(255, 255, 255));
        evAdditionalDetails.setText("Additional Details");

        BookNowBtn.setText("Book Now");
        BookNowBtn.addActionListener(this::BookNowBtnActionPerformed);

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(this::ClearBtnActionPerformed);

        jButton1.setText("Contact US");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Header)
                .addGap(186, 186, 186))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(ClearBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(evGuestcount)
                            .addComponent(evAdditionalDetails)
                            .addComponent(evlocation)
                            .addComponent(evType))
                        .addGap(9, 9, 9)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eventGuestCount, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eventTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(eventAdditionalDetailsScr, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BookNowBtn)
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)
                        .addContainerGap(72, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Header)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evType)
                    .addComponent(eventTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(evlocation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(evGuestcount)
                                .addGap(18, 18, 18)
                                .addComponent(evAdditionalDetails))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(eventGuestCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eventAdditionalDetailsScr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ClearBtn)
                            .addComponent(BookNowBtn)
                            .addComponent(jButton1))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventTypeComboBoxActionPerformed

    private void BookNowBtnActionPerformed(java.awt.event.ActionEvent evt) {

        // 1️⃣ Read form data
        String eventType = eventTypeComboBox.getSelectedItem().toString();
        String location = jComboBox2.getSelectedItem().toString();
        int guestCount = (int) eventGuestCount.getValue();
        String details = enentAdditionalDetailstxt.getText();
       String eventDate = "To be determined";

        
        // 2️⃣ Validate fields
        if (eventType == null || eventType.isEmpty()
               
                || location == null || location.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please fill all required fields"
            );
            return;
        }

        // 3️⃣ Ensure user is logged in
        if (!SessionManager.isLoggedIn()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Session expired. Please login again."
            );
            new Login().setVisible(true);
            this.dispose();
            return;
        }

        // 4️⃣ FileManager
        FileManager fm = new FileManager(
            FileManager.getResourcePath("data/users.txt"),
            FileManager.getResourcePath("data/booking.txt")
        );

        // 5️⃣ Load existing bookings
        ArrayList<Booking> bookings = fm.loadBookings(
            new ArrayList<>(),
            new ArrayList<>()
        );

        // 6️⃣ Generate Booking ID
        int bookingId = fm.generateBookingId(bookings);

        // 7️⃣ Create Event

        Event newEvent = new Event(
            bookingId,        
            eventType,        
            // eventDate,     
            location,         
            guestCount,       
            details          
        );

        // 8️⃣ Booking metadata
        String status = "Completed";
        double totalPrice = 150.0; // can be calculated later

        // 9️⃣ Create Booking (LOGGED-IN CUSTOMER)
        Booking booking = new Booking(
            bookingId,
            (customer) SessionManager.getCurrentUser(),
            newEvent,
            status,
            totalPrice
        );

        // 🔟 Save booking
        bookings.add(booking);
        fm.savingBooking(bookings, fm.getBookingFilePath());

        // 1️⃣1️⃣ Confirmation
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Booking Created Successfully!"
        );
        
        // 1️⃣3️⃣ Send email asynchronously to logged-in customer
        user user = SessionManager.getCurrentUser();

        // Create EmailService object passing the customer email
        EmailService emailService = new EmailService(user.getEmail());

        // Call sendBookingConfirmation on the object
        new Thread(() -> emailService.sendBookingConfirmation(
                user.getName(),
                eventType,
                eventDate,
                location,
                bookingId
        )).start();


        // 1️⃣2️⃣ Navigate to MyBookings
        new MyBookingsScreen().setVisible(true);
        this.dispose();
}                                          

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
                                        
 
    enentAdditionalDetailstxt.setText("");
    eventGuestCount.setValue(1);      
    eventTypeComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        openChatWindow();
    }//GEN-LAST:event_jButton1ActionPerformed

private boolean isValidDate(String dateStr) {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
    sdf.setLenient(false);

    try {
       
        java.util.Date inputDate = sdf.parse(dateStr);
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.setTime(inputDate);
        int year = cal.get(java.util.Calendar.YEAR);

        return year >= 2025; 
    } catch (ParseException e) {
        return false;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookNowBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel Header;
    private javax.swing.JTextArea enentAdditionalDetailstxt;
    private javax.swing.JLabel evAdditionalDetails;
    private javax.swing.JLabel evGuestcount;
    private javax.swing.JLabel evType;
    private javax.swing.JScrollPane eventAdditionalDetailsScr;
    private javax.swing.JSpinner eventGuestCount;
    private javax.swing.JComboBox<String> eventTypeComboBox;
    private javax.swing.JLabel evlocation;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

// ==========================================================
    // ============= كود الشات والتواريخ (إضافات) ===============
    // ==========================================================

    // دالة فتح الشات
    private void openChatWindow() {
        JDialog chatDialog = new JDialog(this, "Contact Project Manager", true);
        chatDialog.setSize(400, 500);
        chatDialog.setLayout(new BorderLayout());
        chatDialog.setLocationRelativeTo(this);

        JTextArea chatArea = new JTextArea();
        chatArea.setEditable(false);
        chatArea.setFont(new Font("Monospaced", Font.PLAIN, 14));
        JScrollPane scroll = new JScrollPane(chatArea);
        chatDialog.add(scroll, BorderLayout.CENTER);

        JPanel bottomPanel = new JPanel(new BorderLayout());
        JTextField inputField = new JTextField();
        JButton btnSend = new JButton("Send");
        JButton btnRefresh = new JButton("Refresh");
        
        JPanel btnPanel = new JPanel(new GridLayout(1, 2));
        btnPanel.add(btnSend);
        btnPanel.add(btnRefresh);

        bottomPanel.add(inputField, BorderLayout.CENTER);
        bottomPanel.add(btnPanel, BorderLayout.EAST);
        chatDialog.add(bottomPanel, BorderLayout.SOUTH);

        // هنا بنجيب اسم اليوزر الحالي من السيشن عشان نعرف مين بيكلم مين
        String myName = "Customer"; 
        if (com.helwan.event_management_system.logic.SessionManager.isLoggedIn()) {
             myName = com.helwan.event_management_system.logic.SessionManager.getCurrentUser().getName();
        }
        String otherSide = "PM";

        loadMessagesFromFile(chatArea, myName);

        String finalMyName = myName; // عشان اللامدا
        btnSend.addActionListener(e -> {
            String msg = inputField.getText().trim();
            if (!msg.isEmpty()) {
                saveMessageToFile(finalMyName, otherSide, msg);
                inputField.setText("");
                loadMessagesFromFile(chatArea, finalMyName);
            }
        });

        btnRefresh.addActionListener(e -> {
            loadMessagesFromFile(chatArea, finalMyName);
        });

        chatDialog.setVisible(true);
    }

    // دالة قراءة الرسائل
    private void loadMessagesFromFile(JTextArea area, String me) {
        area.setText("");
        File file = new File("messages.txt");
        if (!file.exists()) return;

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 3) {
                    String sender = parts[0];
                    String receiver = parts[1];
                    String msg = parts[2];

                    if (sender.equalsIgnoreCase(me) || receiver.equalsIgnoreCase(me)) {
                        if (sender.equalsIgnoreCase(me)) {
                            area.append("Me: " + msg + "\n");
                        } else {
                            area.append(sender + ": " + msg + "\n");
                        }
                        area.append("-----------------\n");
                    }
                }
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    // دالة حفظ الرسائل
    private void saveMessageToFile(String sender, String receiver, String msg) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("messages.txt", true))) {
            bw.write(sender + "," + receiver + "," + msg);
            bw.newLine();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error sending message!");
        }
    }
}
