package com.helwan.event_management_system.UI.booking;

import com.helwan.event_management_system.data.FileManager;
import com.helwan.event_management_system.models.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Adham
 */
public class MyBookingsScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyBookingsScreen.class.getName());
    private FileManager fileManager;
    private customer currentCustomer;

    /**
     * Creates new form MyBookingsScreen
     * @param currentCustomer The logged-in customer
     */
    public MyBookingsScreen(customer currentCustomer) {
        this.currentCustomer = currentCustomer;
        
        // Initialize FileManager with file paths
        this.fileManager = new FileManager();
        
        initComponents();
        loadBookingsData();
    }

    /**
     * Load bookings data into the table
     */
    private void loadBookingsData() {
        try {
            // Load users and events first
            ArrayList<user> users = fileManager.loadUsers();
            ArrayList<Event> events = fileManager.loadEvents();
            
            // Filter only customers from users list
            ArrayList<customer> customers = new ArrayList<>();
            for (user u : users) {
                if (u instanceof customer) {
                    customers.add((customer) u);
                }
            }
            
            // Load all bookings
            ArrayList<Booking> allBookings = fileManager.loadBookings();
            
            // Filter bookings for current customer
            ArrayList<Booking> customerBookings = new ArrayList<>();
            for (Booking booking : allBookings) {
                if (booking.getCustomerId().getId() == currentCustomer.getId()) {
                    customerBookings.add(booking);
                }
            }
            
            // Populate table
            populateTable(customerBookings);
            
            logger.info("Loaded " + customerBookings.size() + " bookings for customer: " + currentCustomer.getName());
            
        } catch (Exception e) {
            logger.severe("Error loading bookings: " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error loading bookings: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Populate the table with booking data
     */
    private void populateTable(ArrayList<Booking> bookings) {
        DefaultTableModel model = (DefaultTableModel) bookingsTable.getModel();
        
        // Clear existing rows
        model.setRowCount(0);
        
        // Add bookings to table
        for (Booking booking : bookings) {
            Object[] row = {
                booking.getBookingId(),
                booking.getEventId().getType(),
                booking.getEventId().getDate(),
                booking.getStatus(),
                String.format("%.2f", booking.getTotalPrice())
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        refreshBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Bookings");

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(this::refreshBtnActionPerformed);

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        bookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Event Type", "Date", "Status", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookingsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(80, 80, 80))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshBtn)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadBookingsData();
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Bookings refreshed successfully!", 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        // Navigate back to previous screen 
         new EVentBookForm().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bookingsTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}